// Auto-generated by fix script: Firebase client initialization for Next.js 13/14+
// Uses browser SDK and must only be imported from client components.
import app, { db, auth } from "@/lib/firebase";

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

// Prevent duplicate inits during HMR and across imports
const app = !getApps().length ? app /* initialized in lib */ : getApp();

export const db = getFirestore(app);
export const auth = getAuth(app);
export default app;
