// Auto-generated by fix script: Firebase Admin initialization for server-side use only.
// Only import from server code / Route Handlers / Server Actions.
import app, { db, auth } from "@/lib/firebase";
import * as admin from "firebase-admin";

if (!admin.apps.length) {
  const key = process.env.FIREBASE_ADMIN_KEY;
  if (!key) {
    // Avoid crashing build; throw only when actually used at runtime.
    console.warn("FIREBASE_ADMIN_KEY is not set. Admin SDK will fail if used.");
  } else {
    try {
      admin.app /* initialized in lib */ ),
      });
    } catch (err) {
      // If already initialized or bad key, log once.
      console.error("Admin init error:", err);
    }
  }
}

export const adminDB = admin.firestore();
export default admin;
